//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteWatson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class analis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public analis()
        {
            this.arquivoanalises = new HashSet<arquivoanalis>();
        }
    
        public int id { get; set; }
        public System.DateTime dtanalise { get; set; }
        public double qtdpalavras { get; set; }
        public string resultado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arquivoanalis> arquivoanalises { get; set; }
    }
}
