//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteWatson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class arquivobase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public arquivobase()
        {
            this.arquivoanalises = new HashSet<arquivoanalise>();
            this.traducaoarquivoes = new HashSet<traducaoarquivo>();
        }
    
        public int id { get; set; }
        public int aluno_id { get; set; }
        public string nome { get; set; }
        public byte[] arquivo { get; set; }
    
        public virtual aluno aluno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arquivoanalise> arquivoanalises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<traducaoarquivo> traducaoarquivoes { get; set; }
    }
}
