//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteWatson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sala
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sala()
        {
            this.alunosporsalas = new HashSet<alunosporsala>();
            this.alunos = new HashSet<aluno>();
        }
    
        public int id { get; set; }
        public int escola_id { get; set; }
        public string ano_escolar { get; set; }
        public string turma { get; set; }
        public string nome { get; set; }
        public short ano_corrente { get; set; }
        public bool ativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alunosporsala> alunosporsalas { get; set; }
        public virtual escola escola { get; set; }

        public virtual ICollection<aluno> alunos{ get; set; }

    }
}
