//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteWatson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class traducaoarquivo
    {
        public int id { get; set; }
        public int arquivobase_id { get; set; }
        public Nullable<int> qtdpalavras { get; set; }
        public Nullable<double> qtdletras { get; set; }
        public string textotraduzido { get; set; }
    
        public virtual arquivobase arquivobase { get; set; }
    }
}
