//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteWatson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_analises
    {
        public int analiseid { get; set; }
        public System.DateTime analisedt { get; set; }
        public int alunoid { get; set; }
        public string alunonome { get; set; }
        public Nullable<int> TotalArquivos { get; set; }
        public string analiseresultado { get; set; }
        public virtual ICollection<view_analises_arquivos> analises_arquivos { get; set; }
    }
}
